### ISSUE TITLE
Motion problems in 0.0.70+ , A/a behaves as i, I doesn't work

### ISSUE THREAD

**Issue by clouedoc** [asvetliakov/vscode-neovim#467]
Hello,

I cannot append to end of line using the A key while inside a { } block.
Here is a gif demonstrating this behaviour

![Dec-29-2020 08-28-18](https://user-images.githubusercontent.com/13921610/103266454-eaa94b80-49af-11eb-9545-002ba30b11a1.gif)

The same behaviour happens with uppercase I (insert) too. It should insert to the beginning of the line but it does not.
The issue still arises:
  - with all extensions disabled
  - without init.vim specified
  - when editing bogus file in another folder
  - when editing other file types (HTML)
  - on Insiders and Stable

The issue does not arises:
  - when using neovim in Terminal.app
  - when the line ends with a (, ), { or }

Notes:
  - latest marketplace version of vscode-neovim
  - ~I'm just going to try to restart my computer and see what happens~ Restarting the computer does not help.

Successful SHIFT+A: (forgot to trim, "Meta" keypress unrelated)
![image](https://user-images.githubusercontent.com/13921610/103268930-c7cd6600-49b4-11eb-9cca-6b1b50a6839a.png)

Faulty SHIFT+A:
![image](https://user-images.githubusercontent.com/13921610/103268954-dd429000-49b4-11eb-8873-c31c94f4bc37.png)

**Workaround for poor souls encountering this issue:** use VSCodeVim in the meantime.

**Comment by Shatur95** [comment]
Can confirm!
Happened after recent #461.

@asvetliakov, sorry, could you take a look?

**Comment by awilkins** [comment]
Can also confirm this bug is occurring, doesn't seem to be bracket based though.

---

1. Normal cursor placed on the `y` of the `adjacency` on the third line
   - <kbd>Shift-A</kbd> works as expected, placing the insert cursor after the last closing brace
   - <kbd>Shift-I</kbd> places the insert cursor immediately before the y
1. Normal cursor placed on the `B` of `BLACK`
   - <kbd>Shift-A</kbd> **and** <kbd>Shift-I</kbd> both place the insert cursor immediately before `B`

```python
    def tick(self):

        adjacency: Dict[Coord, int] = {}

        for coord, tile in self.tiles.items():
            if tile == BLACK:
                for neighbour in self.get_neighbours(coord):
                    adjacency[neighbour] = adjacency.get(neighbour, 0) + 1

```

Happens with this code in it's original file and also pasted to an `enew` untitled buffer, both set to "Plain Text" and "Python"

**Comment by Qizot** [comment]
Yup I thought I broke something but have the same bug as you guys. `A` and `I` don't work as expected, it simply goes into insert mode under the cursor.

**Comment by asvetliakov** [comment]
Can anyone with with issue try with default vscode settings? I can't seem to reproduce by using both code snippets

**Comment by asvetliakov** [comment]
Also try to update neovim to latest nightly

**Comment by Shatur95** [comment]
@asvetliakov, solved the issue for me!

**Comment by awilkins** [comment]
Tried :

- Using an empty init.vim ; no effect
- Reverting to an empty settings file (bar the settings required to get the plugin working, path and key dispatch (remapped escape key) ) : no effect
- Using `code --extensions-dir /tmp/nvim` and then installing this extension only : no effect (in conjunction with fresh settings as above)

`nvim` is `0.5.0+ubuntu2+git202011201111-480b04122-d569569c9-523645f61~ubuntu20.04.1` ; this is from the "Neovim Unstable" PPA for Ubuntu. `480b04` is from 20th November.

- Downloaded `nvim.appimage` from nightly [releases](https://github.com/neovim/neovim/releases/nightly) page
- Added `+x` and placed on path
- Changed nvim path setting in extension to point at `nvim.appimage`

Confirm that all the cases in my comment above now behave properly.

**Comment by asvetliakov** [comment]
awesome, so the problem looks like in neovim ui event differences between latest nightly and old versions. 0.0.63 only worked by `win_viewport` event, in 0.0.70+ that event can be ignored if there is no followed normal cursor goto/scroll event

**Comment by gekoke** [comment]
Had the exact same problem. Getting the latest version of Neovim fixed it for me.

**Comment by thinkjrs** [comment]
It looks like neovim upstream is migrating builds from Travis to Github Actions and several releases aren't done yet. I'm using the snap nightly v0.5.0-654-g3acfefb63 and experience the motion issues.

[Neovim migration tracker](https://github.com/neovim/neovim/issues/13312#issue-745276921)

A really simple workaround is to change your version of the extension in vscode:

![image](https://user-images.githubusercontent.com/16545607/103318456-164e2500-49f4-11eb-94f8-444cc83954c8.png)

And much :heart: to @asvetliakov & contributors -- this is an amazing extension!

**Comment by asvetliakov** [comment]
Anyone is having this problem and *can't upgrade to latest neovim nightly* (especially when win builds are not available yet) - can try to install this build:
https://github.com/asvetliakov/vscode-neovim/suites/1740998941/artifacts/33041509

This is from #473

But my personal recommendation is to use just WSL in this case.

**Comment by pc223** [comment]
TIL vscode silently auto update extensions :joy: I kept staring at the config file to see if I mistyped something 😂

**Comment by mizagog** [comment]
> But my personal recommendation is to use just WSL in this case.

I've been thinking of using WSL for some other vim add-ons that don't work on windows. what Linux disto would you recommend?

**Comment by nrdlab** [comment]
> Had the exact same problem. Getting the latest version of Neovim fixed it for me.

Same here

**Comment by asvetliakov** [comment]
>I've been thinking of using WSL for some other vim add-ons that don't work on windows. what Linux disto would you recommend?

Personally i'm using [ArchLinux](https://github.com/yuk7/ArchWSL) when on Win/WSL. But that's just personal preference

**Comment by ycy3723** [comment]
I got 0.0.73 version. But my issue didn't solved. My A(append) motion always show prepend motion. How can solve it... T.T

![Dec-31-2020 04-24-28](https://user-images.githubusercontent.com/38966985/103376629-91acf500-4b20-11eb-81e1-8c6c08cbcf46.gif)

**Comment by ycy3723** [comment]
> @ycy3723, have you tried to updating Neovim nightly to the latest master?

Yes, latest version is 0.0.73 and I already installed it.

**Comment by Shatur95** [comment]
> Yes, latest version is 0.0.73 and I already installed it.

No, I'm talking about Neovim itself.

**Comment by ycy3723** [comment]
> > Yes, latest version is 0.0.73 and I already installed it.
> 
> No, I'm talking about Neovim itself.

@Shatur95 Thx for your service. Finally I fixed with your tip 👏 👍

**Comment by ian-h-chamberlain** [comment]
Not sure if anyone else ran into this, but I had an issue with upgrading neovim to latest nightly.
Previously I was using `brew install --HEAD neovim` on macOS, but when I upgraded to latest `HEAD`, `nvim` would crash on startup every time, which was even worse than this cursor motion issue, but I fixed it via:

```sh
brew uninstall neovim
brew tap jason0x43/homebrew-neovim-nightly  # this just pulls from the neovim github release page
brew install neovim-nightly
```

Note that since these are unsigned binaries, the first time you run it will complain that it cannot be opened – go to `System Preferences > Security & Privacy > General` and click "Open Anyway". I had to repeat the process 3 types for some unsigned shared libraries also installed by the package.

Hope this helps someone else who was struggling with it like I was!

**Comment by asvetliakov** [comment]
>Previously I was using brew install --HEAD neovim on macOS, but when I upgraded to latest HEAD, nvim would crash on startup every time, which was even worse than this cursor motion issue, but I fixed it via:

Probably need `brew install luajit --HEAD` here too. But for some reason `brew install --HEAD neovim` doesn't work for me at all. I found it much easier to drop tarball somewhere at home and adjust PATH

**Comment by asvetliakov** [comment]
Neovim nightly builds for win are finally available:
https://github.com/neovim/neovim/releases/nightly

**Comment by SpicyRicecaker** [comment]
I downloaded the appimage and zip from the latest nightly build `NVIM v0.5.0-dev+992-gf3a8c930a` (the one that just came with Windows builds) but am still encountering this issue on both Windows and linux even with all extensions disabled and empty init.vim

I then proceeded to build neovim master revisions from around 2 days ago, and each revision seemed to work fine with `0.0.70+` up until commit [b01a60b](https://github.com/neovim/neovim/commit/b01a60b1aaaa6152b58af96c5054f697bbc3a31e). This commit seems to have reverted a past commit. 

Perhaps we should fall back to `0.0.63` for now?

**Comment by asvetliakov** [comment]
@SpicyRicecaker Interesting... does this build work for you with latest nightly? https://github.com/asvetliakov/vscode-neovim/suites/1740998941/artifacts/33041509

**Comment by SpicyRicecaker** [comment]
@asvetliakov that build seems to work just fine on linux with the latest nightly appimage

**Comment by asvetliakov** [comment]
@SpicyRicecaker 
do you have repro snippet? I've just reinstalled neovim through brew (finally started to work for me) and it's working fine. Thanks!

If it's consistent then i'll just merge #473 and release update

**Comment by SpicyRicecaker** [comment]
@asvetliakov 
Sorry, I'm new to contributing, so I don't really know what you mean by repro snippet...
Do you mean how I installed this extension, or neovim?

**Comment by asvetliakov** [comment]
A sample text and steps to reproduce behaviour, same as here: https://github.com/asvetliakov/vscode-neovim/issues/467#issuecomment-752016314

**Comment by SpicyRicecaker** [comment]
@asvetliakov
Gotcha

Running `NVIM v0.5.0-dev+992-gf3a8c930a` with https://github.com/asvetliakov/vscode-neovim/suites/1740998941/artifacts/33041509, empty `init.vim`, `settings.json` empty except for nvim path, no extensions

- Normal cursor placed on the `y` of the `adjacency` on the third line
  - `Shift-A` *seemes to be slightly bugged*, placing the insert cursor on the beginning of the fourth line, while `$` moves to the end of the bracket
  - `Shift-I` works as expected, placing the insert cursor before the a
- Normal cursor placed on the B of BLACK
  - `Shift-A` and `Shift-I` both work as expected

```python
def tick(self):

    adjacency: Dict[Coord, int] = {}
    
    for coord, tile in self.tiles.items():
        if tile == BLACK:
            for neighbor in self.get_neighbors(coord):
                adjacency[neighbor] = adjacency.get(neighbor, 0) + 1
```

Occurs in plaintext file

**Comment by asvetliakov** [comment]
@SpicyRicecaker Sorry , i mean with normal 0.0.73 not with that build

**Comment by SpicyRicecaker** [comment]
@asvetliakov

Running `NVIM v0.5.0-dev+992-gf3a8c930a` appimage on Fedora 33, with `0.0.73`, empty init.vim, settings.json empty except for nvim path, no extensions except for neovim

- Normal cursor placed on the `w` of the `world`
  - `Shift+a` puts cursor before w 
  - `Shift+i` puts cursor before w
  - `a` puts cursor before w
  - `i` puts cursor before w
  
```
Hello world
```

In a basic `text.txt` file

**Comment by asvetliakov** [comment]
Ok, thank you. Curious, why it's working on mac?

**Comment by asvetliakov** [comment]
Ok, finally reproduced with:
```proto
message ChatEntryNoteData {
    // Note
    string note = 1;
}
```
Cursor at `// [Cursor]Note`

**Comment by asvetliakov** [comment]
Fixed and released 0.0.74

**Comment by clouedoc** [comment]
> Fixed and released 0.0.74

Thank you!

**Comment by kar9222** [comment]
@asvetliakov  Some issues for [wellle/targets.vim](https://github.com/wellle/targets.vim). Before 0.0.70+, everything works. After 0.0.70+, text object motion when __unicode__ character present in the same line breaks the motion.

### Bugs after 0.0.70+

Normal cursor placed on `a` of `par1`, press `via` to select 'inside argument' text object `par1`
- Without unicode, `par1` is selected as expected
- With unicode `ŷ`, `par` is selected without the `1`

```jl
y = function(par1)  # Without unicode
ŷ = function(par1)  # With unicode
```

Normal cursor placed on `a` of `par1`, press `cia` to change 'inside argument' text object `par1` and cursor positioned inside bracket `(<my_cursor>)`
- Without unicode, `par1` is deleted and cursor positioned inside bracket `y = function(<my_cursor>)` as expected
- With unicode `ŷ`, `par` is deleted and cursor positioned outside bracket to the left by 1 column `ŷ = function<my_cursor>()`

```jl
y = function(par1)  # Without unicode
ŷ = function(par1)  # With unicode
```

Similar bugs for other related motion...

### Versions

OS: Windows with WSL2

asvetliakov/vscode-neovim 0.0.75: https://github.com/asvetliakov/vscode-neovim/commit/20cba2206f1fd04db4eaccc716b1028f96411194

<details>
  <summary>Local Windows NVIM v0.5.0-dev+992-gf3a8c930a</summary>

  NVIM v0.5.0-dev+992-gf3a8c930a
  Build type: RelWithDebInfo
  LuaJIT 2.1.0-beta3
  Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterpr
  ise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS
  /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONST
  DC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLAR
  ATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LE
  VEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -IC:/pr
  ojects/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -I
  D:/a/neovim/neovim/build/include
  Compiled by runneradmin@fv-az152-708
  
  Features: -acl +iconv +tui
  See ":help feature-compile"
  
     system vimrc file: "$VIM\sysinit.vim"
    fall-back for $VIM: "C:/Program Files/nvim/share/nvim"
  
  Run :checkhealth for more inf
</details>
